version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  calendar_app:
    depends_on:
      - redis
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached
      - gem-volume:/gems
    environment:
      - BASIC_AUTH_USER_NAME=mo@buildbunker.com
      - BASIC_AUTH_PASSWORD=Bunk3r
      - REDISTOGO_URL=redis://172.18.0.2:6379/
volumes:
  gem-volume:
